// examples/vite/src/components/HelloWorld.tsx
export default function HelloWorld({ msg }: { msg: string }) {
  return (
    <>
      <h1>{msg}</h1>
      <p>
        Inspect the element to see the <code>__source</code>
      </p>
      <p>
        <a
          target="_black"
          href="https://github.com/zjxxxxxxxxx/unplugin-vue-source"
        >
          Github
        </a>
      </p>
    </>
  );
}

// examples/vite/src/components/HelloWorld.vue
<script setup lang="ts">
import Notes from "./Notes.vue";
defineProps<{ msg: string }>();
</script>

<template>
  <h1>{{ msg }}</h1>
  <div class="card">
    <Notes />
  </div>
  <p class="read-the-docs">
    <a target="_black" href="https://github.com/zjxxxxxxxxx/open-editor">
      Github
    </a>
  </p>
</template>

<style scoped>
.read-the-docs {
  color: #888;
}
</style>
